#include <stdio.h>  // Standard input-output library for printing lyrics
#include <string.h> // String library for handling text manipulation
#include "DTMFLyrcsHolder.h" // Header file that declares the `dtmfLyrics` variable


const char dtmfLyrics[] = 
    "\nEh-eh, eh-eh, eh-eh, eh-eh\n\n"
    "Otro sunset bonito que veo en San Juan\n"
    "Disfrutando de todas esas cosas que extrañan los que se van\n"
    "Disfrutando de noche' de esas que ya no se dan\n"
    "Que ya no se dan\n"
    "Pero queriendo volver a la última vez\n"
    "Que a los ojos te miré\n"
    "Y contarte las cosas que no te conté\n"
    "(Te parece' a mi crush, jaja)\n"
    "Y tirarte la' foto' que no te tiré\n"
    "(Acho, jura'o te ves bien linda, déjame tirarte una foto)\n"
    "Ey, tengo el pecho pela'o, me dio una matá'\n"
    "El corazón dándome patá'\n"
    "Dime, baby, ¿dónde tú está'?\n"
    "Pa' llegarle con RoRo, Julito, Krystal\n"
    "Roy, Edgar, Seba, Óscar, Darnell y Big Jay, tocando batá\n"
    "Hoy la calle la dejamo' 'esbaratá\n"
    "Y sería cabrón que tú me toque' el güiro\n"
    "Yo veo tu nombre y me salen suspiro'\n"
    "No sé si son petardo' o si son tiro'\n"
    "Mi blanquita, perico, mi kilo\n"
    "Yo estoy en PR, tranquilo, pero\n\n"
    "Debí tirar más fotos de cuando te tuve\n"
    "Debí darte más beso' y abrazo' las vece' que pude\n"
    "Ey, ojalá que los mío' nunca se muden\n"
    "Y si hoy me emborracho, pues que me ayuden\n"
    "Debí tirar más foto' de cuando te tuve\n"
    "Debí darte más beso' y abrazo' las veces que pude\n"
    "Ojalá que los mío' nunca se muden\n"
    "Y si hoy me emborracho, pues que me ayuden\n\n"
    "Ey, hoy voy a estar con abuelo to'l día, jugando dominó\n"
    "Si me pregunta si aún pienso en ti, yo le digo que no\n"
    "Que mi estadía cerquita de ti ya se terminó\n"
    "Ya se terminó, ey\n"
    "Que prendan la' máquina', voy pa' Santurce\n"
    "Aquí todavía se da caña\n"
    "Chequéate las babie', diablo, mami, qué dulce\n"
    "Hoy yo quiero beber, beber, beber\n"
    "Y hablar mierda hasta que me expulsen\n"
    "'Toy bien loco ('Toy bien loco), 'toy bien loco ('Toy bien loco)\n"
    "Cabrón, guía tú, que hasta caminando yo estoy que choco\n"
    "'Toy bien loco ('Toy bien loco), 'toy bien loco ('Toy bien loco)\n"
    "Vamo' a disfrutar, que nunca se sabe si nos queda poco\n\n"
    "Gente, lo' quiero con cojone', los amo\n"
    "Gracias por estar aquí, de verdad\n"
    "Para mí e' bien importante que estén aquí\n"
    "Cada uno de ustede' significa mucho para mí\n"
    "Así que, vamo' pa' la foto, vengan pa'cá\n"
    "Métase to'l mundo, to'l corillo, vamo'\n"
    "Zumba\n\n"
    "Ya Bernie tiene el nene y Jan la nena'\n"
    "Ya no estamo' pa' la movie' y las cadena'\n"
    "'Tamos pa' las cosa' que valgan la pena\n"
    "Ey, pa'l perreo, la salsa, la bomba y la plena\n"
    "Chequéate la mía cómo es que suena\n\n"
    "Debí tirar más fotos de cuando te tuve\n"
    "Debí darte más besos y abrazo' las veces que pude\n"
    "Ojalá que los mío' nunca se muden\n"
    "Y que tú me envíe' más nude'\n"
    "Y si hoy me emborracho, que Beno me ayude\n";



