#include <stdio.h>
#include <string.h>
#include "TitiMePregutno.h"

char titiMePreguntoLyrics[] = 
    "\nTití me preguntó si tengo muchas novia'\n"
    "Muchas novia', hoy tengo a una, mañana a otra, ey\n"
    "Pero no hay boda, tití me preguntó si tengo muchas novia'\n"
    "Muchas novia', hoy tengo a una, mañana a otra\n"
    "Me las voy a llevar a todas pa' un VIP\n"
    "Un VIP, ey, saluden a Titi\n"
    "Vamo' a tirarnos un selfie, say, \"Cheese\"\n"
    "Que sonrían las que ya les metí en un VIP\n"
    "Un VIP, ey, saluden a Titi\n"
    "Vamo' a tirarnos un selfie, say, \"Cheese\"\n"
    "Que sonrían las que ya se olvidaron de mí\n\n"
    "Me gustan mucho las Gabriela, las Patricia\n"
    "Las Nicole, las Sofía\n"
    "Mi primera novia en Kinder, María\n"
    "Y mi primer amor se llamaba Thalía\n"
    "Tengo una colombiana que me escribe to' los día'\n"
    "Y una mexicana que ni yo sabía\n"
    "Otra en San Antonio que me quiere todavía\n"
    "Y las de PR que toditas son mías\n"
    "Una dominicana que juga' bombón\n"
    "Juga' bombón, la de Barcelona\n"
    "Que vino en avión y dice que mi bicho está cabrón\n"
    "Yo dejo que vuelvan y se vayan otra vez\n"
    "Yo soy un cabrón, no me enamoro otra vez\n"
    "No me enamoro otra vez\n\n"
    "Tití me preguntó si tengo muchas novia'\n"
    "Muchas novia', hoy tengo a una, mañana a otra, ey\n"
    "Pero no hay boda, tití me preguntó si tengo muchas novia'\n"
    "Ey, ey, muchas novia', hoy tengo a una, mañana a otra\n\n"
    "Ey, ey, ey\n"
    "Yo quisiera enamorarme\n"
    "Pero no puedo, pero no puedo, uh, uh\n"
    "Yo quisiera enamorarme\n"
    "Pero no puedo, pero no puedo\n"
    "Sorry, yo no confío, yo no confío\n"
    "Nah, ni en mí mismo confío\n"
    "Si quiere' quedarte hoy, quédate\n"
    "¿Qué carajo se va a hacer? Aquí estamos al garete\n"
    "Si es bonito y me llora, me conmueve\n"
    "Un día me enamoro, pero otro día me mueve\n\n"
    "Tití me preguntó si tengo muchas novia'\n"
    "Muchas novia', hoy tengo a una, mañana a otra, ey\n"
    "Pero no hay boda, tití me preguntó si tengo muchas novia'\n"
    "Ey, ey, muchas novia', hoy tengo a una, mañana a otra\n\n"
    "Ey, ey, ey\n"
    "Tití me preguntó\n"
    "Tití me preguntó\n"
    "Tití me preguntó\n"
    "Tití me preguntó\n";
